### ISSUE TITLE
train error => loop

### ISSUE THREAD

**Issue by ghost** [yahoo/YaraParser#2]
i train YaraParser with intruction in the readme file. but below Exceptions Occur. and go into a loop.
result is : 

D:\nlp\Parser\YaraParser-0.2>     java -jar jar/YaraParser.jar train  -train-fil
e sample_data/train.conll  -dev sample_data/dev.conll -model /tmp/model iter:10
 -punc punc_files/google_universal.puncs
train file: sample_data/train.conll
dev file: sample_data/dev.conll
cluster file:
beam width: 64
rootFirst: false
labeled: true
lower-case: false
extended features: true
extended with brown cluster features: false
updateModel: max violation
oracle: dynamic
oracle selection: latent max
training-iterations: 10
number of threads: 8
partial training starting iteration: 3

CoNLL data reading done!
size of training data (#sens): 1279
1000...
iteration 1 took 25 seconds

saving the model...Exception in thread "main" java.io.FileNotFoundException: \tm
p\model_iter1 (The system cannot find the path specified)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at Structures.InfStruct.saveModel(InfStruct.java:122)
        at TransitionBasedSystem.Trainer.ArcEagerBeamTrainer.train(ArcEagerBeamT
rainer.java:91)
        at Parser.YaraParser.train(YaraParser.java:116)
        at Parser.YaraParser.main(YaraParser.java:30)

**Comment by yuvalpinter** [comment]
If there is no existing \tmp dir on your system, create it, or just change the -model location to somewhere existing where you know you have write permissions.

**Comment by ghost** [comment]
yes. this is right. 
i change model location and parser works correctly.
thanks
